[env:m5stack-atom]
platform = espressif32
board = m5stack-atom
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-6D528A1346
monitor_port = /dev/cu.usbserial-6D528A1346
lib_deps =
  bblanchon/ArduinoJson@^7.4.2
  knolleary/PubSubClient@^2.8
